version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: conversion-app-mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
            MYSQL_USER: ${DB_USERNAME:-user}
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p$${DB_PASSWORD:-root}"]
            timeout: 20s
            retries: 10
volumes:
    db_data:
        driver: local
